version : '3'
services:
  postgres: 
    container_name:  postgres_container
    image: postgres
    environment:  
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: assessmentDb
    ports: 
      - 5432:5432
    volumes: 
      - postgres-data:/var/lib/postgresql/data

  pgadmin: 
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    ports: 
      - 5050:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

  api:
    container_name: api_container
    build: .
    ports:
      - "8000:80"
    depends_on: 
      - postgres
    environment:
      CUSTOMCONNSTR_POSTGRES: "host=postgres_container;port=5432;database=assessmentDb;username=postgres;password=admin;"

volumes: 
  postgres-data: 
  pgadmin-data: 
